### ISSUE TITLE
No SBCL or CCL on the command line

### ISSUE THREAD

**Issue by vindarel** [40ants/base-lisp-image#2]
Hi,
So I tried this image, and once inside it, and in bash, there is no `sbcl` nor `ccl` command. `ros run` is ok.
Is that expected ?

```
# sbcl
bash: sbcl: command not found
root@f8ba16f09330:/app# /usr/bin/sbcl
bash: /usr/bin/sbcl: No such file or directory
```

I ran it like in your example with the added `bash`:

    ... 40ants/base-lisp-image:latest-sbcl bash

without bash, I do enter a lisp repl correctly.

thanks

**Comment by xenophonf** [comment]
You have to run SBCL or whatever using Roswell.  From https://github.com/roswell/roswell/wiki#usage:

```sh
$ ros list installed sbcl   # list the installed implementations
$ ros run -- --version      # check which implementation is used
SBCL 1.2.15
$ ros use sbcl/1.2.3        # change the default implementation
```

**Comment by svetlyak40wt** [comment]
@xenophonf is right.
